// Date: 12/04/2016 17:38:30
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer body;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer tail;
    ModelRenderer headNeck;
    ModelRenderer horn;
    ModelRenderer horn2;
    ModelRenderer head;
    ModelRenderer ear2;
    ModelRenderer ear1;
  
  public ModelNew()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      body = new ModelRenderer(this, 34, 11);
      body.addBox(-5F, -10F, -7F, 7, 13, 8);
      body.setRotationPoint(1F, 11F, 2F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 1.570796F, 0F, 0F);
      leg1 = new ModelRenderer(this, 56, 0);
      leg1.addBox(0F, 0F, -1F, 2, 6, 2);
      leg1.setRotationPoint(-3.5F, 18F, 3F);
      leg1.setTextureSize(64, 32);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 48, 0);
      leg2.addBox(-2F, 0F, -1F, 2, 6, 2);
      leg2.setRotationPoint(2.5F, 18F, 3F);
      leg2.setTextureSize(64, 32);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 40, 0);
      leg3.addBox(0F, 0F, -1F, 2, 6, 2);
      leg3.setRotationPoint(-3.5F, 18F, -6F);
      leg3.setTextureSize(64, 32);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 32, 0);
      leg4.addBox(-2F, 0F, -1F, 2, 6, 2);
      leg4.setRotationPoint(2.5F, 18F, -6F);
      leg4.setTextureSize(64, 32);
      leg4.mirror = true;
      setRotation(leg4, 0F, 0F, 0F);
      tail = new ModelRenderer(this, 24, 14);
      tail.addBox(0F, 0F, -1F, 1, 1, 4);
      tail.setRotationPoint(-1F, 12F, 5F);
      tail.setTextureSize(64, 32);
      tail.mirror = true;
      setRotation(tail, 0F, 0F, 0F);
      
	  
	  
	  headNeck = new ModelRenderer(this, 0, 0);
      headNeck.addBox(-3F, -4F, -3F, 6, 4, 3);
      headNeck.setRotationPoint(-0.5F, 10F, -5F);
      headNeck.setTextureSize(64, 32);
      headNeck.mirror = true;
      setRotation(headNeck, 0F, 0F, 0F);
      
	  horn = new ModelRenderer(this, 30, 24);
      horn.addBox(0F, -3F, 0F, 1, 3, 1);
      horn.setRotationPoint(1F, 2F, -7F);
      horn.setTextureSize(64, 32);
      horn.mirror = true;
      setRotation(horn, -0.4363323F, 0F, 0F);
     
	 horn2 = new ModelRenderer(this, 30, 28);
      horn2.addBox(-1F, -3F, 0F, 1, 3, 1);
      horn2.setRotationPoint(-2F, 2F, -7F);
      horn2.setTextureSize(64, 32);
      horn2.mirror = true;
      setRotation(horn2, -0.4363323F, 0F, 0F);
      
	  head = new ModelRenderer(this, 0, 20);
      head.addBox(-3F, -4F, -8F, 6, 4, 8);
      head.setRotationPoint(-0.5F, 6F, -5F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
     
	 ear2 = new ModelRenderer(this, 48, 8);
      ear2.addBox(-3F, 0F, 0F, 3, 1, 1);
      ear2.setRotationPoint(-3F, 4F, -8F);
      ear2.setTextureSize(64, 32);
      ear2.mirror = true;
      setRotation(ear2, 0F, 0F, 0F);
     
	 ear1 = new ModelRenderer(this, 56, 8);
      ear1.addBox(0F, 0F, 0F, 3, 1, 1);
      ear1.setRotationPoint(2F, 4F, -8F);
      ear1.setTextureSize(64, 32);
      ear1.mirror = true;
      setRotation(ear1, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    body.render(f5);
    leg1.render(f5);
    leg2.render(f5);
    leg3.render(f5);
    leg4.render(f5);
    tail.render(f5);
    headNeck.render(f5);
    horn.render(f5);
    horn2.render(f5);
    head.render(f5);
    ear2.render(f5);
    ear1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
